### ISSUE TITLE
Merging multiple datasets in one operation

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/DelayEmbeddings.jl#112]
Is it possible to merge multiple `Dataset`s into one larger `Dataset` using a single operation, say splatting a tuple of `Datasets` like `Dataset(ds...)`?

For example, if I have three `Dataset{2}` with the same length, I can do the following to obtain a `Dataset{6}`.

```julia
julia> x, y, z = Dataset([1:10 2:11]), Dataset([3:12 4:13]), Dataset([5:14 6:15])
julia> Dataset(Dataset(x, y), z)
6-dimensional Dataset{Int64} with 10 points
  1   2   3   4   5   6
  2   3   4   5   6   7
  3   4   5   6   7   8
  4   5   6   7   8   9
  5   6   7   8   9  10
  6   7   8   9  10  11
  7   8   9  10  11  12
  8   9  10  11  12  13
  9  10  11  12  13  14
 10  11  12  13  14  15
```

But I'd like to be able to just `Dataset(x, y, z, ...)`, potentially with more than three variables. It is of course possible to do nested calls to the `Dataset` constructor, but that leads to ugly code. The following doesn't work, but it would be nice if it did:

```julia
julia> Dataset(x, y, z)
ERROR: MethodError: no method matching Dataset(::Dataset{2, Int64}, ::Dataset{2, Int64}, ::Dataset{2, Int64})
Closest candidates are:
  Dataset(::AbstractDataset{D1, T}, ::AbstractDataset{D2, T}) where {D1, D2, T} at ~/.julia/packages/DelayEmbeddings/Lcs5l/src/datasets/dataset.jl:206
  Dataset(::Vector{<:Real}, ::AbstractDataset{D, T}) where {D, T} at ~/.julia/packages/DelayEmbeddings/Lcs5l/src/datasets/dataset.jl:208
  Dataset(::Dataset) at ~/.julia/packages/DelayEmbeddings/Lcs5l/src/datasets/dataset.jl:163
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[52]:1
```

And the following creates a dataset of datasets:

```julia
julia> Dataset([x, y, z])
1-dimensional Dataset{Dataset{2, Int64}} with 3 points
 2-dimensional Dataset{Int64} with 10 points
 2-dimensional Dataset{Int64} with 10 points
 2-dimensional Dataset{Int64} with 10 points
```

**Comment by Datseris** [comment]
Why not just call `append!`? 

The syntax `Dataset(x, y, z)` with `x,y,z` being `Dataset`s doesn't make sense for appending the datasets. Try to do the same with `Vector`, and you'll make a vector of vectors.

`merge!` is the function you are looking for I think.  SO a PR extending `merge!` for datasets should be done.

**Comment by Datseris** [comment]
Actually, forge that. `append!` is what you want. It already exists: https://github.com/JuliaDynamics/DelayEmbeddings.jl/blob/main/src/datasets/dataset.jl#L86

we trivially need to extend it to `append!(d, args...)` so that it can allow more than 1 datasets.

**Comment by Datseris** [comment]
Ah no, you want to merge in the horizontal direction, not vertical. `hcat` is what you want, which is also implemented. https://github.com/JuliaDynamics/DelayEmbeddings.jl/blob/main/src/datasets/dataset.jl#L109

but once agian needs to be extended to allow more than 2 arguments.

**Comment by kahaaga** [comment]
> Ah no, you want to merge in the horizontal direction, not vertical. hcat is what you want,

Precisely.

I propose the following, which allows for any number of datasets to be horizontally concatenated, and each of the datasets can have different dimensions. 

```julia
function hcat_new(xs::Vararg{AbstractDataset{D, T} where {D}, N}) where {T, N}
    Ls = length.(xs)
    maxlen = maximum(Ls)
    all(Ls .== maxlen) || error("Datasets must be of same length")
    D = sum(dimension.(xs))
    v = Vector{SVector{D, T}}(undef, maxlen)
    for i = 1:minlen
        v[i] = SVector{D, T}(Iterators.flatten(xs[d][i] for d = 1:N)...,)
    end
    return Dataset(v)
end
```

Performance is identical to the existing `hcat` for two input datasets.

```julia
julia> D1 = Dataset(rand(10000, 2))
julia> D2 = Dataset(rand(10000, 3))
julia> D3 = Dataset(rand(10000, 2)); 
julia> hcat(D1, D2); hcat_new(D1, D2); hcat(D1, D2, D3)

julia> @btime hcat($D1, $D2);
  9.709 μs (2 allocations: 390.67 KiB)
  
julia> @btime hcat_new($D1, $D2);
9.792 μs (2 allocations: 390.67 KiB)

julia> @btime hcat_new($D1, $D2, $D3);
13.083 μs (2 allocations: 468.80 KiB)
```

**Comment by Datseris** [comment]
There is no reason for `hcat_new`, `hcat` itself is the name you should use.

**Comment by kahaaga** [comment]
> There is no reason for hcat_new, hcat itself is the name you should use.

Sure, that was just for demonstration purposes. I'll submit a PR with the updated `hcat`.

**Comment by kahaaga** [comment]
This can be closed now, right?
