### ISSUE TITLE
Function ```estimate_dimension``` is missing from ```separated_de/estimate_dimension.jl```

### ISSUE THREAD

**Issue by CNelias** [JuliaDynamics/DelayEmbeddings.jl#133]
**Describe the bug**
When trying to call the function estimate_dimension e.g. as ``` estimate_dimension(signal,  ...)``` the following error is returned:
```Julia
ERROR: UndefVarError: `estimate_dimension` not defined
Stacktrace:
 [1] getproperty
   @ .\Base.jl:31 [inlined]
 [2] avg_dimension(sigs::Matrix{Float64})
   @ Main d:\Corentin\Julia\Glial_mitochondria\src\mitochondrial_dynamics.jl:34
 [3] top-level scope
   @ d:\Corentin\Julia\Glial_mitochondria\src\mitochondrial_dynamics.jl:57
```

Looking at the source code in ```separated_de/estimate_dimension.jl``` there seems to be no such function there, as opposed to the function estimate_delay, which is found in estimate_delay.jl

**Minimal Working Example**
```
using DynamicalSystems
using Random
test = rand(1000)
 estimate_dimension(signal)
```

**Package versions**

```julia 1.10
DyncamicalSystems 3.2.3
```

**Comment by Datseris** [comment]
`estimate_dimension` does not appear to be an exported name of DelayEmbeddings.jl:

https://juliadynamics.github.io/DelayEmbeddings.jl/stable/search/?q=estimate_dimension

where did you find it from?

**Comment by CNelias** [comment]
In the docs (https://juliadynamics.github.io/DynamicalSystems.jl/v1.3/embedding/estimate/)

![image](https://github.com/JuliaDynamics/DelayEmbeddings.jl/assets/34754896/d7e6c633-1a4c-4041-8639-14f79b01f19a)

**Comment by Datseris** [comment]
This links to version of the 1.3 docs, which is 6 years old, probably older. Current version of the software is 3.2.3 as also stated in your report of package versions. I assume this issue is because of consluting a by-now invalid documentation page. Use instead the current one (https://juliadynamics.github.io/DynamicalSystemsDocs.jl/delayembeddings/stable/) and if there are still problems with missing names re-open the issue!

**Comment by Datseris** [comment]
Or, if you want to stick to using the v1.3 docs, that is also doable but you need to explicitly add v1.3 of DynamicalSystems.jl at your project.

**Comment by CNelias** [comment]
Oh my bad, sorry for the trouble. I was using the first link that google provided me for the doc...

**Comment by Datseris** [comment]
Perhaps I can fix that. Do you remember what was the query you used in google? All queries I've tried now bring me either to the latest stable version or to the development version (which is the same as latest stable).

**Comment by kahaaga** [comment]
Same result here when using Google as the search engine. The first link leads to the correct docs, the fourth link leads to some very old docs.

<img width="669" alt="Skjermbilde 2024-01-11 kl  13 30 02" src="https://github.com/JuliaDynamics/DelayEmbeddings.jl/assets/5237566/5bd2fe6e-20a8-4c81-aa8e-ec43455d9a37">

**Comment by Datseris** [comment]
I found this that I will test: https://discourse.julialang.org/t/ann-documenter-0-27/62726#warnings-and-seo-for-outdated-docs-1
