### ISSUE TITLE
Feature request: Pecora method

### ISSUE THREAD

**Issue by pucicu** [JuliaDynamics/DelayEmbeddings.jl#17]
There is a great idea for time delay embedding that outperforms the simple approach. It was described in Pecora et al: _A unified approach to attractor reconstruction_, Chaos **17**, 2007 ([http://dx.doi.org/10.1063/1.2430294](http://dx.doi.org/10.1063/1.2430294)). 

It would be nice to have this algorithm included.

**Comment by Datseris** [comment]
For Hacktoberfest: this can be accepted as multiple PRs. It is not a difficult thing to do, but it is certainly lengthy.
