### ISSUE TITLE
Increase efficiency of `_average_a`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DelayEmbeddings.jl#3]
AT the moment
```
function _average_a(s::AbstractVector{T},γ,τ) where T
    #Sum over all a(i,d) of the Ddim Reconstructed space, equation (2)
    R1 = reconstruct(s,γ+1,τ)
    R2 = reconstruct(s[1:end-τ],γ,τ)
```
However it is clear that from here:
```
    for (i, γ) ∈ enumerate(γs)
        aafter = _average_a(s, γ+1, τ)
        E1s[i] = aafter/aprev
        aprev = aafter
    end
```
each reconstruction is actually done twice! This is inefficient and instead `R2` should be replaced by `R1` in each iteration. This will lead to type instability, but it may be faster anyway.

**Comment by heliosdrm** [comment]
What about a variant of `_average_a` that also returns `R1`, and takes it in the next iteration as `R2`? (The tail of `R1` should be trimmed before being used as `R2` in the next iteration, but that is not a big issue.)

Besides, it might be worth to explore if the time series with `γ+1` temporal neighbors (`R1`) may be obtained from the series with `γ` neighbors (`R2`), more efficiently than calculating it directly from `s`.

Note: this optimization only makes sense if we are sure that the iterator `γs` is a series of consecutive integers.

**Comment by Datseris** [comment]
Cancel the above, it works super fast if within a function!

```
julia> f(s, r) = vcat(s, SVector{1}(r))

julia> @btime f($s, $r)
  1.093 ns (0 allocations: 0 bytes)
4-element SArray{Tuple{4},Float64,1,4}:
 0.2711836952994944
 0.9316699266892112
 0.8007346927728582
 0.7754873329767022
```

**Comment by heliosdrm** [comment]
Found a better solution: it is not necessary to calculate R1, because we only need to update distances between the nearest neighbors of R2, and this can be done with the values of the original time series (no reconstruction needed). I'm preparing a PR with this.
