### ISSUE TITLE
The Takens embedding theorem

### ISSUE THREAD

**Issue by sgjanssens** [JuliaDynamics/DelayEmbeddings.jl#7]
This is just a minor note on language.

At the moment you spell it as "Taken's Theorem" - at least in the README - while  its eponym was called "Takens" by family name. Therefore we usually refer to it as "Takens' theorem" or just "the Takens theorem".

**Comment by Datseris** [comment]
Thanks for the info!

This seems like a very easy fix. Do you want to open a Pull Request where you solve this issue? This will (forever) list you as a contributor to this repository. Otherwise, I'll do it.

**Comment by sgjanssens** [comment]
No, it would be silly if that would list me as a contributor. It was a small thing I happened to notice and it is surely fine when you solve it. Thank you and success with JuliaDynamics!
