### ISSUE TITLE
setindex! neither errors nor does its job

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DelayEmbeddings.jl#83]
Either we should properly implement this or have it error.
The current behaviour is clearly suboptimal.

```
julia> using DelayEmbeddings

julia> d = Dataset(rand(5,3))
3-dimensional Dataset{Float64} with 5 points
 0.43156   0.979782  0.649049
 0.451744  0.649936  0.383886
 0.328286  0.199782  0.36327
 0.450927  0.799212  0.628991
 0.677224  0.199356  0.233859

julia> d[:, 1] .= 0
5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

julia> d
3-dimensional Dataset{Float64} with 5 points
 0.43156   0.979782  0.649049
 0.451744  0.649936  0.383886
 0.328286  0.199782  0.36327
 0.450927  0.799212  0.628991
 0.677224  0.199356  0.233859
```

The current bug appears to stem from the fact that the method is not implemented
and the fallback relies on `Base.dotview`.
However 
```
julia> Base.dotview(d, :, 1)
5-element Vector{Float64}:
 0.43155961790952047
 0.45174350165887
 0.3282862209053605
 0.4509268888889679
 0.6772237874813112
```
this is clearly not a view....

**Comment by Datseris** [comment]
Good catch. Super surprised that this doesn't error...

for full data points, `A[i] = ...` I think this works normally.

But I think the tests here are not good, we should test `setindex!` extensively.

`d[:, 1] .= 0` *can* work, but it will allocate more than "expected" as it will have to create all poiints, not just their first coordinate, given that `SVector` is immutable.

For a quick fix we can just throw an error.

**Comment by kahaaga** [comment]
> d[:, 1] .= 0 can work, but it will allocate more than "expected" as it will have to create all poiints, not just their first coordinate, given that SVector is immutable.

This remind me of an old feature request I *think* I discussed with you @Datseris, which is to allow `MVector` as points in a `Dataset`. If using mutable vectors, `d[:, 1] .= 0` would work without extra allocations. This is still something that would be useful for me, so I could try implementing it.

**Comment by Datseris** [comment]
Sure, we only have to adjust the type decleration of `Dataset` to not enforce `SVector` but be parameterized to its `data::Vector{X}` with `X<:AbstractVector`.

**Comment by Datseris** [comment]
I'm trying to solve this, but I don't know how to throw an error on `d[:, i] .= 0`. Broadcasting internals is something I have 0 clue about.

**Comment by Datseris** [comment]
fixed
